name: fl_admin_dashboard
description: "Dashboard Flutter"
publish_to: "none"
version: 0.3.0

environment:
  sdk: ^3.5.3

dependencies:
  email_validator: ^3.0.0
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  get_storage: ^2.1.1
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  http: ^1.2.2
  riverpod_annotation: ^2.6.1
  url_strategy: ^0.3.0

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/json/
    - assets/svg/
