name: fl_admin_dashboard
description: "Dashboard Flutter"
publish_to: "none"
version: 0.3.0

environment:
  sdk: ^3.8.0

dependencies:
  email_validator: ^3.0.0
  file_picker: ^9.2.3
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  get_storage: ^2.1.1
  go_router: ^15.2.4
  google_fonts: ^6.2.1
  riverpod_annotation: ^2.6.1
  hooks_riverpod: ^2.6.1
  talker_flutter: ^4.9.1
  talker_riverpod_logger: ^4.9.1
  talker_dio_logger: ^4.9.1
  get_it: ^8.0.3
  dio: ^5.8.0+1
  flutter_hooks: ^0.21.2
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.6.10
  flutter_hooks_lint: ^1.3.1
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  package_rename: ^1.10.0
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/json/
    - assets/svg/
