name: fl_admin_dashboard
description: "Dashboard Flutter"
publish_to: "none"
version: 0.2.0

environment:
  sdk: ^3.5.3

dependencies:
  dio: ^5.7.0
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  get_storage: ^2.1.1
  go_router: ^14.2.8
  google_fonts: ^6.2.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/json/
    - assets/svg/
